# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScR-tqHVu2CpF7WcultNx0O6tQycjJQv
"""

import pandas as pd
baza={
    "FISH":[  "QOSIMJONOV SHERZODBEK", "RAXIMJONOVA MOHIDIL","QADAMOVA ZULAYXO","AXMADJONOV DIYORBEK","PRIMBERDIYEV DILSHODBEK","IBROHIMOVA ADOLATXON","ASADULLAYEV SAFARALI","ALIKSEYIVA HADICHAXON","MADKARIMOV ABBOSXON" ],
    "YOSHI":[  "21","20","28","19","19","19","19","20","19"  ],
    "JINSI":[  "OGIL BOLA", "QIZ BOLA","QIZ BOLA","OGIL BOLA","OGIL BOLA","QIZ BOLA","OGIL BOLA","QIZ BOLA","OGIL BOLA"  ],
    "QAYSI UNIVERSITETDA OQISHI":["TATU","PALTEX","TATUFF","TATU","TATU","TATU","TATU","TATU","TATU"  ],
    "MANZILI":[ "MARGILON SHAXAR","UCHKOPRIK TUMAN","MARGILON SHAXAR","ANDIJON SHAXAR","QOQN SHAXAR","BUXORO SHAXAR","TOSHLOQ TUMAN","TOSHLOQ TUMAN","BESHARIQ TUMAN"  ],


}
db=pd.DataFrame(baza)
print(db)

filtr=db[(db["JINSI"]=="QIZ BOLA")&(db["YOSHI"]<'20') ]
print(filtr)

